### ISSUE TITLE
Modals are not displaying

### ISSUE THREAD

**Issue by vipdorian** [ashvin777/framework7.angular2#1]
To reproduce, browse https://ashvin777.github.io/framework7.angular2/www/#/modals and click on Alert

**Comment by ashvin777** [comment]
Hi Vipdorian,

Thanks for you feedback. Actually currently this project is under dev. So I am yet to integrate the Framework 7 components for those all items which you have raised as an issue. Just give me few more days then I will be able to showcase the fully working Kitchen Sink app. 

Regards,
Ashvin

**Comment by vipdorian** [comment]
Hi Ashvin,
Thank you for your answer.
I am working with a team of 3 programmers on a project using F7 + Angular2.
We are using currently http://embed.plnkr.co/KTzAqu0OQrP3ZmHpuGy8/
but we would really like to use your template because it uses angular2
standards.
If you intend to maintain it, me and my team are willing to provide usefull
and constructive feedback on you repo.

Regards,
Dorian


2016-09-19 21:01 GMT-04:00 Ashvin Kumar Suthar <notifications@github.com>:

**Comment by ashvin777** [comment]
That's great. I will be definitely able to help you. 

Just fyi, this project used the Core JavaScript version of Angular 2 instead of TypeScript.

**Comment by ashvin777** [comment]
Hi Dorian,

i did something for the modals. Have a look on the same link. Enjoy !! :)

Regards,
Ashvin

**Comment by vipdorian** [comment]
Hi Ashvin, thanks, I will follow up your work!
